# Generated by Django 2.2 on 2019-04-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecuacionesNoLineales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecuacionesnolineales',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ecuacionesnolineales',
            name='tittle',
        ),
        migrations.AddField(
            model_name='ecuacionesnolineales',
            name='extremo_inf',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ecuacionesnolineales',
            name='extremo_sup',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ecuacionesnolineales',
            name='funcion',
            field=models.TextField(default='x', max_length=50),
        ),
        migrations.AddField(
            model_name='ecuacionesnolineales',
            name='iter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ecuacionesnolineales',
            name='tol',
            field=models.IntegerField(default=1),
        ),
    ]
