# Generated by Django 2.1.7 on 2019-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcuacionesNoLineales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=60)),
                ('valor_inicial', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('iter', models.IntegerField()),
            ],
        ),
    ]
