# Generated by Django 2.1.7 on 2019-03-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecuacionesNoLineales', '0002_auto_20190317_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecuacionesnolineales',
            old_name='iter',
            new_name='iterr',
        ),
    ]
